nelmio_api_doc:
    documentation:
        info:
            title: Github score app
            description: Calculates the score as positive number / (positive number + negative number)
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns: # an array of regexps
            - ^/(?!api|_error)
